Zbang.Zbox.Mvc3WebRole/Controllers/BoxController.cs
using DevTrends.MvcDonutCaching;
using System;
using System.Linq;
using System.Security;
using System.Web.Mvc;
using System.Web.UI;
using Zbang.Zbox.Domain.Commands;
using Zbang.Zbox.Domain.Common;
using Zbang.Zbox.Infrastructure.Consts;
using Zbang.Zbox.Infrastructure.Enums;
using Zbang.Zbox.Infrastructure.Exceptions;
using Zbang.Zbox.Infrastructure.Security;
using Zbang.Zbox.Infrastructure.ShortUrl;
using Zbang.Zbox.Infrastructure.Trace;
using Zbang.Zbox.Mvc3WebRole.Attributes;
using Zbang.Zbox.Mvc3WebRole.Controllers.Resources;
using Zbang.Zbox.Mvc3WebRole.Factories;
using Zbang.Zbox.Mvc3WebRole.Helpers;
using Zbang.Zbox.Mvc3WebRole.Models;
using Zbang.Zbox.ReadServices;
using Zbang.Zbox.ViewModel.Queries;
using Zbang.Zbox.ViewModel.Queries.Autocomplete;

namespace Zbang.Zbox.Mvc3WebRole.Controllers
{
    [SessionState(System.Web.SessionState.SessionStateBehavior.Disabled)]
    [ZboxHandleError(ExceptionType = typeof(UnauthorizedAccessException), View = "Error")]
    public class BoxController : BaseController
    {
        public BoxController(IZboxWriteService zboxWriteService,
            IZboxReadService zboxReadService,
            IShortCodesCache shortToLongCache,
            IFormsAuthenticationService formsAuthenticationService)
            : base(zboxWriteService, zboxReadService, shortToLongCache, formsAuthenticationService)
        { }
        /// <summary>
        /// Page of box view
        /// </summary>
        /// <param name="BoxUid">The short id of box</param>
        /// <returns>box view</returns>
        [HttpGet]
        [NoCache]
        [ZboxAuthorize(IsAuthenticationRequired = false)]
        public ActionResult Index(string BoxUid)
        {
            var userId = GetUserId(false);
            try
            {
                if (string.IsNullOrEmpty(BoxUid))
                    return RedirectToAction("Index", "Dashboard");
                ViewBag.boxid = BoxUid;
                var boxId = m_ShortToLongCode.ShortCodeToLong(BoxUid);
                var query = new GetBoxQuery(boxId, userId);
                var result = m_ZboxReadService.GetBox2(query);
                return View("Index2", result);
            }
            catch (BoxAccessDeniedException)
            {
                return View("Error");
            }
            catch (BoxDoesntExistException)
            {
                return View("Error");
            }
            catch (Exception ex)
            {
                TraceLog.WriteError(string.Format("Box Index BoxUid {0} userid {1}", BoxUid, userId), ex);
                return View("Error");
            }
        }


        [HttpPost]
        [NoCache]
        [ZboxAuthorize(IsAuthenticationRequired = false)]
        public ActionResult Items(string BoxUid, int pageNumber)
        {
            var userId = GetUserId(false); // not really needs it
            try
            {
                var boxId = m_ShortToLongCode.ShortCodeToLong(BoxUid);
                var query = new GetBoxItemsPagedQuery(boxId, userId);
                var result = m_ZboxReadService.GetBoxItemsPaged2(query);
                return Json(new JsonResponse(true, result));
            }
            catch (Exception ex)
            {
                TraceLog.WriteError(string.Format("Box Items BoxUid {0} pageNumber {1} userId {2}", BoxUid, pageNumber, userId), ex);
                return Json(new JsonResponse(false));
            }
        }

        [HttpPost]
        [NoCache]
        [ZboxAuthorize(IsAuthenticationRequired = false)]
        public ActionResult Updates(string BoxUid, DateTime UserLastSync)
        {

            if (string.IsNullOrEmpty(BoxUid))
                return new HttpStatusCodeResult(500);
            var boxId = m_ShortToLongCode.ShortCodeToLong(BoxUid);
            var userId = GetUserId(false);

            var query = new GetBoxUpdatesQuery(boxId, userId, UserLastSync.AddSeconds(-30));
            var result = m_ZboxReadService.GetBoxUpdate(query);

            return Json(new JsonResponse(true, result));

        }



        [ChildActionOnly]
        [NoCache]
        [ZboxAuthorize(IsAuthenticationRequired = false)]
        public ActionResult BoxPermissionByUser(string BoxUid)
        {
            var boxId = m_ShortToLongCode.ShortCodeToLong(BoxUid);
            var userId = GetUserId(false);
            var permission = GetUserPermission(userId, boxId);
            if (!permission.CanUserSeeData)
            {
                throw new SecurityException(BoxControllerResources.BoxSettingsNotAllowed); // unathorized exception doesnt raise http 500 it seems
            }
            return PartialView("_BoxPermissionByUser", permission);
        }

        [ChildActionOnly]
        [NoCache]
        [ZboxAuthorize(IsAuthenticationRequired = false)]
        public ActionResult UserPermission(string BoxUid)
        {
            var boxId = m_ShortToLongCode.ShortCodeToLong(BoxUid);
            var userId = GetUserId(false);
            var permission = GetUserPermission(userId, boxId);
            if (!permission.CanUserSeeData)
            {
                throw new SecurityException(BoxControllerResources.BoxSettingsNotAllowed); // unathorized exception doesnt raise http 500 it seems
            }
            return PartialView("UserPermission", permission);
        }

        [ZboxAuthorize(IsAuthenticationRequired = false)]
        [Ajax, HttpPost]
        public JsonResult Members(string BoxUid)
        {
            if (string.IsNullOrWhiteSpace(BoxUid))
            {
                return Json(new JsonResponse(false));
            }
            var boxId = m_ShortToLongCode.ShortCodeToLong(BoxUid);
            var userId = GetUserId(false);
            var result = m_ZboxReadService.GetBoxMembers(new GetBoxQuery(boxId, userId));

            return Json(new JsonResponse(true, result));
        }

        [ZboxAuthorize]
        public ActionResult Settings(string BoxUid)
        {
            if (string.IsNullOrEmpty(BoxUid))
                throw new ArgumentException("Box id is missing");
            var boxId = m_ShortToLongCode.ShortCodeToLong(BoxUid);
            var userId = GetUserId();

            var query = new GetBoxQuery(boxId, userId);
            var result = m_ZboxReadService.GetBoxSetting(query);

            var model = new BoxSetting()
            {
                Name = result.Name,
                Notification = result.NotificationSetting,
                Privacy = result.PrivacySetting
            };
            ViewBag.UserType = result.UserType;
            return PartialView("_Settings2", model);
        }

        [HttpPost]
        [ZboxAuthorize]
        public ActionResult Settings(BoxSetting model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new JsonResponse(false, GetModelStateErrors()));
            }
            try
            {
                var boxId = m_ShortToLongCode.ShortCodeToLong(model.Uid);
                var userId = GetUserId();
                if (model.Privacy.HasValue)
                {
                    ChangePrivacySettings(model.Privacy.Value, model.Uid, userId);
                }

                var commandBoxName = new ChangeBoxNameCommand(boxId, userId, model.Name);
                m_ZboxWriteService.ChangeBoxName(commandBoxName);

                var command = new ChangeNotificationSettingsCommand(boxId, userId, model.Notification);
                m_ZboxWriteService.ChangeNotificationSettings(command);


                return Json(new JsonResponse(true));
            }
            catch (UnauthorizedAccessException)
            {
                return Json(new JsonResponse(false, "You don't have permission"));
            }
        }

        /// <summary>
        /// Used by global serach to get template for boxes
        /// </summary>
        /// <returns></returns>
        [ChildActionOnly]
        [ZboxAuthorize]
        [DonutOutputCache(VaryByParam = "none", Duration = TimeConsts.Week, VaryByCustom = "Lang")]
        public ActionResult Template()
        {
            return PartialView("_Template");
        }

        //[HttpPost]
        //[ZboxAuthorize]
        //public ActionResult Tags(string term)
        //{
        //    var userId = GetUserId();
        //    var result = m_ZboxReadService.GetTagsByPrefix(new GetTagsQuery(userId, term));
        //    return Json(new JsonResponse(true, result));
        //}


        //[HttpPost]
        //[ZboxAuthorize]
        //public ActionResult SaveTag(string tagName, string BoxUid)
        //{
        //    if (string.IsNullOrWhiteSpace(BoxUid))
        //    {
        //        return Json(new JsonResponse(false, new { error = "BoxUid cannot be null" }));
        //    }
        //    if (string.IsNullOrWhiteSpace(tagName))
        //    {
        //        return Json(new JsonResponse(false, new { error = "tagName cannot be null" }));
        //    }

        //    var boxId = m_ShortToLongCode.ShortCodeToLong(BoxUid);
        //    var userId = GetUserId();
        //    m_ZboxWriteService.AddTagToBox(new AddTagToBoxCommand(Guid.NewGuid(), boxId, new[] { tagName }, userId));
        //    return Json(new JsonResponse(true));
        //}
        //[HttpPost]
        //[ZboxAuthorize]
        //public ActionResult DeleteTag(string tagName, string BoxUid)
        //{
        //    if (string.IsNullOrWhiteSpace(BoxUid))
        //    {
        //        return Json(new JsonResponse(false, new { error = "BoxUid cannot be null" }));
        //    }
        //    if (string.IsNullOrWhiteSpace(tagName))
        //    {

Zbang.Zbox.Mvc3WebRole/Views/Shared/_Footer.cshtml
@using Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources
@using Zbang.Zbox.Infrastructure.Culture
<footer>
    <ul class="footer">
        <li>&copy;@DateTime.UtcNow.Year.ToString()&nbsp;@FooterResources.ZbangIt&nbsp;V @VersionHelper.CurrentVersion()</li>
        <li><a href="@Url.Action("AboutUs", "Home")">@FooterResources.AboutUs</a></li>
        <li><a href="@Url.Action("ContactUs", "Home")">@FooterResources.ContactUs</a></li>
        <li><a href="@Url.Action("Privacy", "Home")">@FooterResources.PrivacyPolicy</a></li>
        <li class="removePipe"><a href="@Url.Action("TermsOfService", "Home")">@FooterResources.TermsOfService</a></li>
        @if (ViewBag.Language != null && ViewBag.Language)
        {
            <li class="addPipe">@Html.ActionLink(Languages.EnglishName, "ChangeLanguage", new { language = Languages.GetLanguageDetailByName(Languages.EnglishName).Culture, source = ViewBag.source }, new { @class = "eng-flag", title = "English site" })</li>
            <li class="removePipe">@Html.ActionLink(Languages.HebrewName, "ChangeLanguage", new { language = Languages.GetLanguageDetailByName(Languages.HebrewName).Culture, source = ViewBag.source }, new { @class = "heb-flag", title = "Hebrew site" })</li>
        }
    </ul>
</footer>

Zbang.Zbox.Mvc3WebRole/Views/Shared/_Layout2.cshtml
@using Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources
@using Zbang.Zbox.Mvc3WebRole.App_Start
<!DOCTYPE html>

<html>
<head>
    <title>@SharedResources.MultiMiCloud</title>
    <link rel="SHORTCUT ICON" href="@Url.Content("~/favicon.ico")"/>


    <meta http-equiv="X-UA-Compatible" content="IE=EDGE" />
    <meta charset="utf-8" content="text/html" http-equiv="content-type" />
    <meta name="viewport" content="width=device-width, maximum-scale=1.0" />

    <meta name="title" content="@ViewBag.metaTitle" />
    <meta name="description" content="@ViewBag.metaDescription" />
    <link rel="image_src" href="@Url.CdnContent("/Images/mmcloud.jpg")"" />

    <meta property="og:site_name" content="MultiMi Cloud" />
    <meta property="og:image" content="@Url.CdnContent("/Images/mmcloud.jpg")"/>
    <meta property="og:title" content="@ViewBag.metaTitle"/>
    <meta property="og:type" content="website" />
    <meta property="og:url" content="@Request.Url.AbsoluteUri" />

    @Html.Css2("newcore")
    @Html.CssRtl("newrtl")

    @RenderSection("Header", false)
    <!--[if lt IE 9]>
        <script>
        document.createElement('header');
        document.createElement('nav');
        document.createElement('section');
        document.createElement('article');
        document.createElement('aside');
        document.createElement('footer');
        document.createElement('hgroup');
        </script>
    <![endif]-->
</head>
<body>
    <header class="mainHeader">
        <div class="wrap">
            @{Html.RenderPartial("TopMenu/_Logo");
              if (User.Identity.IsAuthenticated)
              {
                  Html.RenderPartial("TopMenu/_Actions");
              }
              Html.RenderAction("GetUserDetail2", "Account", true); 
              if (User.Identity.IsAuthenticated)
              {
                  Html.RenderPartial("TopMenu/_Search");
              }
              
            }
        </div>
    </header>
    @if (ViewBag.topbar != null)
    {
        <div class="topbar @ViewBag.topbar clearfix">
            <div class="wrap">
                @RenderSection("TopBar", false)
            </div>
        </div>
    }
    @if (ViewBag.title != null && ViewBag.title)
    {
        <div class="title clearfix">
            <div class="wrap">@RenderSection("Title", false)</div>
        </div>
    }
    @if (ViewBag.lowerbar != null && ViewBag.lowerbar)
    {
        <div class="lowerbar clearfix">
            <div class="wrap">@RenderSection("LowerBar", false)</div>
        </div>
    }
    <div class="page clearfix" id="MainContent">
        <div class="wrap">
            @RenderBody()
        </div>
    </div>
    @{
        
        Html.RenderPartial("_Footer");
        @*TODO: this is not good should be ajaxy*@
        Html.RenderPartial("_UploadDialog");
        Html.RenderPartial("_Invite");
        Html.RenderPartial("_Message");

        //Html.RenderPartial("_Confirm");
    }
    @Html.Script2("newCode")
    <script type="text/javascript" src="@Url.UICultureContent("~/Js/Resource/ZboxResources.js")" ></script>

</body>
</html>

Zbang.Zbox.Mvc3WebRole/Views/Shared/_Layout3.cshtml
@using Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources
@using Zbang.Zbox.Mvc3WebRole.App_Start
<!DOCTYPE html>

<html>
<head>
    <title>@SharedResources.MultiMiCloud</title>
    <link rel="SHORTCUT ICON" href="@Url.Content("~/favicon.ico")"/>


    <meta http-equiv="X-UA-Compatible" content="IE=EDGE" />
    <meta charset="utf-8" content="text/html" http-equiv="content-type" />
    <meta name="viewport" content="width=device-width, maximum-scale=1.0" />

    <meta name="title" content="@ViewBag.metaTitle" />
    <meta name="description" content="@ViewBag.metaDescription" />
    <link rel="image_src" href="@Url.CdnContent("/Images/mmcloud.jpg")"" />

    <meta property="og:site_name" content="MultiMi Cloud" />
    <meta property="og:image" content="@Url.CdnContent("/Images/mmcloud.jpg")"/>
    <meta property="og:title" content="@ViewBag.metaTitle"/>
    <meta property="og:type" content="website" />
    <meta property="og:url" content="@Request.Url.AbsoluteUri" />

    @Html.Css2("newcore3")
    @Html.CssRtl("newrtl3")

    @RenderSection("Header", false)
    <!--[if lt IE 9]>
        <script>
        document.createElement('header');
        document.createElement('nav');
        document.createElement('section');
        document.createElement('article');
        document.createElement('aside');
        document.createElement('footer');
        document.createElement('hgroup');
        </script>
    <![endif]-->
</head>
<body>

    <!-- Sidebar here -->
    <aside>
        <a class="navigation" href="/"><header class="txtshd1">cloudents</header></a>
        <div class="header2 txtshd1">Your Academic location online</div>
        @{Html.RenderAction("GetUserDetail3", "Account", true);}

        <a href="@Url.Action("Index", "Dashboard")" class="userAreaBtn navigation">
            <span>My Area</span>
            <div id="btnMy" class="btnArrow"></div>
        </a>
        <a href="@Url.Action("Index", "Library")" class="userAreaBtn lib navigation">
            <span>Library</span>
            <div id="btnLib" class="btnArrow"></div>
        </a>

        <div class="contentBlock" id="invites">
            <div class="contentHeader invitation">Invitations</div>
            <ul data-bind="foreach:invites">
                <li>
                    <a data-bind="attr:{ href: '@Url.Action("Index", "Box")?boxuid=' + id }">
                        <span class="invboxName" data-bind="text: name"></span>
                        <span class="invboxOwner">@Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources.SharedResources.Owner:&nbsp;<span class="ownerName elps" data-bind="text:owner"></span></span>
                    </a></li>
            </ul>
        </div>

       @* <div class="contentBlock">
            <div class="contentHeader update">Updates</div>
            <ul>
                <li>Neta Fisher invited you to the box 'Student Pictures 2013'</li>
                <li>Neta Fisher invited you to the box 'Student Pictures 2013'</li>
                <li>Neta Fisher invited you to the box 'Student Pictures 2013'</li>
            </ul>
        </div>

        <div class="ad"></div>
        <div class="ad"></div>*@
    </aside>

    <div class="bodyContent" id="main">
        @RenderBody()
    </div>

    <script type="text/javascript" src="@Url.UICultureContent("~/Js/Resource/ZboxResources.js")" ></script>
    @Html.Script2("cd1")

</body>
</html>

Zbang.Zbox.Mvc3WebRole/Views/Shared/_UploadLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    @using Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources
    <title>@SharedResources.MultiMiCloud</title>
    @Html.Css2("upload")
    @Html.CssRtl("rtl")
    @Html.Script2("jquery")
</head>
<body>
    <div class="wrap">
        <div id="Header" class="ZboxTitle">
            <img src="@Url.CdnContent("/images/logo.jpg")" alt="@SharedResources.MultiMiCloud" title="@SharedResources.MultiMiCloud" />
            <span class="verTitle">@SharedResources.Beta</span>
        </div>
        <div id="MainContent">
            @RenderBody()
        </div>
    </div>

    @Html.Script2("upload")
    <script type="text/javascript" src="@Url.UICultureContent("~/Js/Resource/ZboxResources.js")" ></script>
    @RenderSection("script", false)
</body>
</html>