Zbang.Zbox.Mvc3WebRole/Models/Message.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using Zbang.Zbox.Mvc3WebRole.Models.Resources;

namespace Zbang.Zbox.Mvc3WebRole.Models
{
    public class Message
    {
        [Required(ErrorMessageResourceType = typeof(InvitationResources), ErrorMessageResourceName = "FieldRequired")]
        [Display(ResourceType = typeof(InvitationResources), Name = "To")]
        public string[] Recepients { get; set; }

        [DataType(DataType.MultilineText)]
        public string Note { get; set; }

        //[Required]
        [HiddenInput(DisplayValue = false)]
        public string BoxUid { get; set; }

        [HiddenInput(DisplayValue = false)]
        public string ItemUid { get; set; }


        public override string ToString()
        {
            return string.Format("Recepients {0} PersonalNote {1} BoxUid {2} ItemUid {3} ", string.Join(";", Recepients), Note, BoxUid, ItemUid);

        }
    }
}

Zbang.Zbox.Mvc3WebRole/Controllers/ShareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI;
using DevTrends.MvcDonutCaching;
using Zbang.Zbox.Domain.Commands;
using Zbang.Zbox.Infrastructure.Consts;
using Zbang.Zbox.Infrastructure.Enums;
using Zbang.Zbox.Infrastructure.Trace;
using Zbang.Zbox.Mvc3WebRole.Attributes;
using Zbang.Zbox.Mvc3WebRole.Helpers;
using Zbang.Zbox.Mvc3WebRole.Models;
using Zbang.Zbox.ViewModel.DTOs;
using Zbang.Zbox.ViewModel.Queries;
using System.Web.Routing;
using Zbang.Zbox.Domain.Common;
using Zbang.Zbox.ReadServices;
using Zbang.Zbox.Infrastructure.ShortUrl;
using Zbang.Zbox.Infrastructure.Security;

namespace Zbang.Zbox.Mvc3WebRole.Controllers
{
    [SessionState(System.Web.SessionState.SessionStateBehavior.Disabled)]
    public class ShareController : BaseController
    {
        protected const string SessionInviteKey = "Invites";

        public ShareController(IZboxWriteService zboxWriteService,
            IZboxReadService zboxReadService,
            IShortCodesCache shortToLongCache,
            IFormsAuthenticationService formsAuthenticationService)
            : base(zboxWriteService, zboxReadService, shortToLongCache, formsAuthenticationService)
        { }

        [HttpPost]
        [ZboxAuthorize]
        public ActionResult InviteBox(Message model)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    return Json(new JsonResponse(false, GetModelStateErrors()));
                }
                if (string.IsNullOrWhiteSpace(model.BoxUid))
                {
                    return Json(new JsonResponse(false, "BoxUid is required"));
                }

                //var privacySettingChanged = false;

                var userId = GetUserId();
                var boxId = m_ShortToLongCode.ShortCodeToLong(model.BoxUid);
                var query = new GetBoxQuery(boxId, userId);
                var boxSettingResult = m_ZboxReadService.GetBoxSetting(query);
                if (boxSettingResult.PrivacySetting == BoxPrivacySettings.Private)
                {
                    var boxPrivacyCommand = new ChangeBoxPrivacySettingsCommand(userId, boxId, BoxPrivacySettings.MembersOnly, string.Empty);
                    m_ZboxWriteService.ChangeBoxPrivacySettings(boxPrivacyCommand);
                }
                var shareCommand = new ShareBoxCommand(boxId, userId, model.Recepients, model.Note);
                m_ZboxWriteService.ShareBox(shareCommand);

                //RemoveBoxUserCaching(userId);
                return Json(new JsonResponse(true));
            }
            catch (UnauthorizedAccessException ex)
            {
                ModelState.AddModelError(string.Empty, "You do not have permission to share a box");
                TraceLog.WriteError(string.Format("InviteBox user: {0} model: {1}", GetUserId(), model.ToString()), ex);
                return Json(new JsonResponse(false, GetModelStateErrors()));
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return Json(new JsonResponse(false, GetModelStateErrors()));
            }
            catch (Exception ex)
            {

                TraceLog.WriteError(string.Format("InviteBox user: {0} model: {1}", GetUserId(), model.ToString()), ex);
                ModelState.AddModelError(string.Empty, "Unsepcified error. try again later");
                return Json(new JsonResponse(false, GetModelStateErrors()));
            }
        }

        [HttpPost]
        [ZboxAuthorize]
        public ActionResult MailShare(Message model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new JsonResponse(false, GetModelStateErrors()));
                }
                if (string.IsNullOrWhiteSpace(model.BoxUid))
                {
                    return Json(new JsonResponse(false, "BoxUid is required"));
                }
                var userId = GetUserId();
                var boxId = m_ShortToLongCode.ShortCodeToLong(model.BoxUid);
                var url = string.Empty;
                if (string.IsNullOrEmpty(model.ItemUid))
                {
                    url = Url.Action("Index", "Box",
                        new RouteValueDictionary(new { BoxUid = model.BoxUid })
                        , Request.Url.Scheme, null);
                }
                else
                {
                    url = Url.Action("Index", "Item",
                        new RouteValueDictionary(new { BoxUid = model.BoxUid, ItemUid = model.ItemUid })
                        , Request.Url.Scheme, null);
                }

                var command = new SendMessageToEmailCommand(userId, model.Recepients,
                    model.Note, url);
                m_ZboxWriteService.SendMessage(command);
                return Json(new JsonResponse(true));
            }
            catch (Exception ex)
            {
                TraceLog.WriteError(string.Format("SendMessage user: {0} model: {1}", GetUserId(), model), ex);
                ModelState.AddModelError(string.Empty, "Unsepcified error. try again later");
                return Json(new JsonResponse(false, GetModelStateErrors()));
            }
        }

        [HttpPost]
        [ZboxAuthorize]
        public ActionResult Message(Message model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return Json(new JsonResponse(false, GetModelStateErrors()));
                }
                var userId = GetUserId();
                var command = new SendMessageToEmailCommand(userId, model.Recepients,
                        model.Note, string.Empty);
                m_ZboxWriteService.SendMessage(command);
                return Json(new JsonResponse(true));
            }
            catch (Exception ex)
            {
                TraceLog.WriteError(string.Format("SendMessage user: {0} model: {1}", GetUserId(), model), ex);
                ModelState.AddModelError(string.Empty, "Unsepcified error. try again later");
                return Json(new JsonResponse(false, GetModelStateErrors()));
            }
        }

        [HttpPost]
        [ZboxAuthorize]
        public ActionResult SubscribeToBox(string BoxUid)
        {
            var boxid = m_ShortToLongCode.ShortCodeToLong(BoxUid);
            var userid = GetUserId();
            var command = new SubscribeToSharedBoxCommand(userid, boxid);
            m_ZboxWriteService.SubscribeToSharedBox(command);
            //RemoveInvitesFromSession();
            return Json(new JsonResponse(true));

        }

        [HttpPost]
        [ZboxAuthorize]
        public ActionResult DeclineInvatation(string BoxUid)
        {
            try
            {
                var boxid = m_ShortToLongCode.ShortCodeToLong(BoxUid);
                var userid = GetUserId();
                var command = new DeleteUserFromBoxCommand(userid, userid, boxid);
                m_ZboxWriteService.DeleteUserFromBox(command);
                //RemoveInvitesFromSession();
                return Json(new JsonResponse(true));
            }
            catch (Exception ex)
            {
                TraceLog.WriteError(string.Format("DeclineInvatation user: {0} BoxUid: {1}", GetUserId(), BoxUid), ex);
                return Json(new JsonResponse(false));
            }
        }

        [ZboxAuthorize(IsAuthenticationRequired = false)]//we need that because of verify account this happen - so infinite loop
        [OutputCache(Duration = TimeConsts.Minute, VaryByParam = "none", Location = OutputCacheLocation.Client, NoStore = true)]
        [HttpGet]
        [Ajax]
        public ActionResult Invites()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return Json(new JsonResponse(true, new string[0]), JsonRequestBehavior.AllowGet);
            }
            var userid = GetUserId();
            try
            {
                //var invites = Session[SessionInviteKey] as IEnumerable<InviteDto>;
                //if (invites == null)
                //{
                    var query = new GetInvitesQuery(userid);
                   var invites = m_ZboxReadService.GetInvites(query);
                   // Session[SessionInviteKey] = invites;
                //}
                return Json(new JsonResponse(true, invites), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                //RemoveInvitesFromSession();
                //RemoveInvitesFromSession();
                TraceLog.WriteError("Share Invites userid " + userid, ex);
                return Json(new JsonResponse(true, new string[0]), JsonRequestBehavior.AllowGet);
            }
        }

        //[NonAction]
        //protected void RemoveInvitesFromSession()
        //{
        //    Session.Remove(SessionInviteKey);
        //}
    }
}

Zbang.Zbox.Mvc3WebRole/Views/Shared/Partials/_Activity.cshtml
@using Zbang.Zbox.Mvc3WebRole.Views.Comment.Resources
@model string
<div class="activitySection" id="commentsSection" data-strap="comment">
    <h4 class="sectiontitle">@Model</h4>
    <form class="clearfix newBoxComment" data-bind="submit: addComment">
        <textarea id="CommentText" placeholder="@CommentResources.ShareYourThoughts" class="inputText commentTextarea"></textarea>
        <button class="btn2 rFloat" type="submit" style="display: none;">@CommentResources.Send</button>
    </form>
    <ol id="CommentList" class="commentList" data-bind="template: { name: 'comment-template', foreach: comments }">
    </ol>
    @{Html.RenderPartial("_CommentTemplate");}
</div>

Zbang.Zbox.Mvc3WebRole/Views/Shared/Partials/_CommentTemplate.cshtml
@using Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources

<script defer="defer" type="text/html" id="wall-template">
    <li class="wallPost clearfix">
        @*<span class="commentDelete"></span>*@
        <img alt="" class="userImg" data-bind="attr: {src: userImg}" width="32" height="32" />
        <div class="commentDetails">
            <a class="commentH1 elps dotChar" data-bind="text: userName"></a><span class="commentTime" data-bind="text:date"></span>
            <a class="commentH2 elps" data-bind="text: 'Box: ' + boxName, attr: { href : boxurl}"></a>
            <div class="commentText" data-bind="html: comment">
            </div>
            <!-- ko if: item -->
            <a data-bind="attr: { href : itemurl}" class="commentItem">
                <img alt="" class="itemThumb" data-bind="attr:{ src: itemPic}" />
                <div class="itemDetails">
                    <span class="commentH3 elps" data-bind="text: itemName"></span>
                    <span class="commentH4 elps" data-bind="text: boxName"></span>
                </div>
            </a>
            <!-- /ko -->
        </div>
        <!-- ko if: isComment -->
        <a class="rFloat commentAction">@SharedResources.Reply</a>
        <!-- /ko -->
    </li>
    <!-- ko if: isComment -->
    <li class="commentReply clearfix" style="display: none">
        <form data-bind="submit: $root.addReply">
            <img alt="" class="lFloat userImg" src="/images/EmptyState/icon_boxplaceholder_01.png" width="32" height="32" />
            <div class="textAreaCtrl">
                <textarea class="inputText commentTextarea clearfix" placeholder="@SharedResources.WriteComment"></textarea>
            </div>
            <button type="submit" class="rFloat btn2">@SharedResources.Reply</button>
        </form>
    </li>
    <ol class="reply" data-bind="template: { name:'comment-template', foreach: replies }"></ol>
    <!-- /ko -->
</script>

<script defer="defer" type="text/html" id="comment-template">
    <li class="comment clearfix">
        <!-- ko if: deleteAllow -->
        <span class="commentDelete" data-bind="click: $root.removeComment"></span>
        <!-- /ko -->
        <img alt="" class="userImg" data-bind="attr: {src: userImg}" width="32" height="32" />
        <div class="commentDetails">
            <a class="commentH1 elps dotChar" data-bind="text: userName"></a><span class="commentTime" data-bind="text:date"></span>
            <!-- ko if: item -->
            <a class="commentH2 elps" data-bind="text: itemName, attr: { href : itemurl}"></a>
            <!-- /ko -->
            <div class="commentText" data-bind="html: comment">
            </div>
        </div>
        <!-- ko if: isComment -->
        <a class="rFloat commentAction">@SharedResources.Reply</a>
        <!-- /ko -->
    </li>
    <!-- ko if: isComment -->
    <li class="commentReply clearfix" style="display: none">
        <form data-bind="submit: $root.addReply">
            <img alt="" class="lFloat userImg" src="@Url.CdnContent("/images/usrPic.png")" width="32" height="32" />
            <div class="textAreaCtrl">
                <textarea class="inputText commentTextarea clearfix" placeholder="@SharedResources.WriteComment"></textarea>
            </div>
            <button class="rFloat btn2" type="submit">@SharedResources.Reply</button>
        </form>
    </li>

    <ol class="reply" data-bind="template: { name:'comment-template', foreach: replies }"></ol>
    <!-- /ko -->
</script>

Zbang.Zbox.Mvc3WebRole/Views/Shared/Partials/_Confirm.cshtml
@using Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources

<div class="popupWrppr confirm txtshd1" id="ConfirmPop">
    <header class="popupHeader popupGradient"></header>
    <div class="message"></div>
    
    <input type="submit" class="btn1 next"/>
    <input type="button" class="btn2 cancel" value="@UploadDialogResources.Cancel" />
    
    <button class="closeDialog shareSprite"></button>
</div>

Zbang.Zbox.Mvc3WebRole/Views/Shared/Partials/_Invite.cshtml
@using Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources

<div class="popupWrppr invite" data-strap="invitapp">
    <header class="popupHeader popupGradient"><span class="invHeader">@UploadDialogResources.InviteTo</span>&nbsp;‎“<span id="iboxName" class="iBoxName"></span>”‎‎</header>
    @using (Ajax.BeginForm("InviteBox", "Share", null, new AjaxOptions
    {
        HttpMethod = "Post",
        OnSuccess = "mmc.inviteSuccess",
        //OnBegin = "Share.ValidateShareForm"
    }, new { id = "fInvite", @class = "popupForm" }))
    {
        Html.RenderPartial("_MailPopUp", new Zbang.Zbox.Mvc3WebRole.Models.Message { BoxUid = ViewBag.boxid }); 
        <button type="button" class="closeDialog shareSprite"></button>
        <input type="submit" class="btn1 next" value="@UploadDialogResources.Send"/>
        <input type="button" id="iCancel" class="btn2 cancel" value="@UploadDialogResources.Cancel" />
   }

</div>

Zbang.Zbox.Mvc3WebRole/Views/Shared/Partials/_MailPopUp.cshtml
@model Zbang.Zbox.Mvc3WebRole.Models.Message
@*<span class="summaryerror"></span>*@

@Html.ValidationSummary()
<div class="inputText inviteUser">
    @Html.LabelFor(m => m.Recepients, new { @class = "inputLabel" })
    <ul id="@(ViewContext.FormContext.FormId)inviteList" class="inviteList">
    </ul>
    <input id="@(ViewContext.FormContext.FormId)inviteInput" class="inviteInput" type="text" placeholder="@Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources.UploadDialogResources.UsernameOr" />
</div>
<button type="button" id="@(ViewContext.FormContext.FormId)imprtCntct" disabled="disabled" class="addInvite upldSprite"></button>

@Html.TextAreaFor(m => m.Note, new { @class = "inputText inviteMsg", id = ViewContext.FormContext.FormId + "Note" })
@Html.HiddenFor(m => m.BoxUid)
@Html.HiddenFor(m => m.ItemUid)

Zbang.Zbox.Mvc3WebRole/Views/Shared/Partials/_Message.cshtml
@using Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources

<div class="popupWrppr share txtshd1" data-strap="msgdiag">
    <header class="popupHeader popupGradient">Send a message</header>
    @using (Ajax.BeginForm("Message", "Share", null, new AjaxOptions
    {
        HttpMethod = "Post",
        OnSuccess = "mmc.messageSuccess",
        //OnBegin = "Share.ValidateShareForm"
    }, new { id = "fMessage", @class = "popupForm" }))
    {
        Html.RenderPartial("_MailPopUp", new Zbang.Zbox.Mvc3WebRole.Models.Message { BoxUid = ViewBag.boxid });
    
        <input type="submit" class="btn1 next" value="@UploadDialogResources.Send"/>
        <input type="button" class="btn2 cancel" value="@UploadDialogResources.Cancel" />
    }
    <button class="closeDialog shareSprite"></button>
</div>

Zbang.Zbox.Mvc3WebRole/Views/Shared/Partials/_RegisterPopUp.cshtml
@using Zbang.Zbox.Mvc3WebRole.Views.Global.Resources

<div id="regPopup">
    <div class="joinNow">@RegisterPopupResources.JoinNow</div>
    <div>@RegisterPopupResources.SignUpAsMember</div>
    <div class="regPopupBtns">
        <button class="btn2" id="signUpNow">@RegisterPopupResources.SignUpNow</button>
        <button id="joinLater" class="btn3">@RegisterPopupResources.OrJoinLater</button>
    </div>
</div>

Zbang.Zbox.Mvc3WebRole/Views/Shared/Partials/_Share.cshtml
@using Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources

<div class="popupWrppr share txtshd1" data-strap="shrapp">
    <header class="popupHeader popupGradient"><span class="sHeader">@SharedResources.Share</span>&nbsp;‎“<span id="sboxName" class="sBoxName elps"></span>”‎</header>
    <input disabled id="sUrl" class="inputText urlInput" type="text" value="@Request.Url"  />
    <button class="btn2" id="CopyLink">@SharedResources.Copy
        <span id="sCopyLink"></span>
    </button>
    <ul id="addthisIcons" class="addThis">
        <li>
            <a>
                <span  class="email shareSprite" id="openMail" title="@SharedResources.Email"></span>
            </a>
        </li>
        <li>
            <a class="addthis_button_facebook">
                <span class="fb shareSprite" title="@SharedResources.SendToFacebook"></span>
            </a>
        </li>
        <li>
            <a class="addthis_button_twitter">
                <span  class="twitter shareSprite" title="@SharedResources.TweetThis"></span>
            </a>
        </li>
    </ul>
    <div id="separatorV" class="separatorV"></div>
    @using (Ajax.BeginForm("MailShare", "Share", null, new AjaxOptions
    {
        HttpMethod = "Post",
        OnSuccess = "mmc.shareSuccess"
    }, new { id = "fShare", @class = "popupForm" }))
    {
        Html.RenderPartial("_MailPopUp", new Zbang.Zbox.Mvc3WebRole.Models.Message { BoxUid = ViewBag.boxid });
    
        <input type="submit" class="btn1 next" value="@UploadDialogResources.Send"/>
        <input type="button" class="btn2 cancel" value="@UploadDialogResources.Cancel" />
    }
    <button class="closeDialog shareSprite"></button>
</div>

Zbang.Zbox.Mvc3WebRole/Views/Shared/Partials/_UploadAddLink.cshtml
@model Zbang.Zbox.Mvc3WebRole.Models.AddLink
@using Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources

@using (Ajax.BeginForm("Link", "Upload", null, new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "mmc.addLinkSuccess"
}, new { @class = "addUrlHolder", id = "fAddLink" }))
{
    
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    @Html.HiddenFor(m => m.BoxId, new { id = "addLinkBox" })
    @Html.TextBoxFor(m => m.Url, new { placeholder = UploadDialogResources.AddUrl, @class = "inputText addUrl" })
    <button id="submitUrl" type="submit" class="btn4 rFloat">@UploadDialogResources.Add</button>
    @Html.ValidationMessageFor(m => m.Url, null, new { @class = "errmsg" })
    
}

Zbang.Zbox.Mvc3WebRole/Views/Shared/Partials/_UploadContainer.cshtml
<div class="uploadContainer">
    <button class="boxUploadbtn" data-strap="upload"><span class="uploadImg"></span>@Zbang.Zbox.Mvc3WebRole.Views.Box.Resources.IndexResources.Upload</button>
</div>

Zbang.Zbox.Mvc3WebRole/Views/Shared/Partials/_UploadCreateAcademicBox.cshtml
@model Zbang.Zbox.Mvc3WebRole.Models.CreateAcademicBox
@using Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources
@*@using (Ajax.BeginForm("CreateAcademic", "Boxes", null, new AjaxOptions
    {
        HttpMethod = "POST",
        OnSuccess = "mmc.createBoxSuccess"
    }
    , new { @class = "type current", id = "Academic" }))
{*@
<div id="createAcademicBoxDialog" title="Create new course" style="display:none;">
    @using (Html.BeginForm("CreateBox", "Library", FormMethod.Post, new { @class = "type current", id = "Academic" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(false)
        <div class="section">
            <div class="courseName">
                @Html.LabelFor(m => m.CourseName, new { @class = "required" })
                @Html.TextBoxFor(m => m.BoxName, new { @class = "inputText", id = "academicBoxName" })
            </div>
            <div class="courseCode">
                @Html.LabelFor(m => m.CourseId)
                @Html.TextBoxFor(m => m.CourseId, new { @class = "inputText" })
            </div>
        </div>

        <div class="section">
            <div class="professor">
                @Html.LabelFor(m => m.Professor)
                @Html.TextBoxFor(m => m.Professor, new { @class = "inputText", placeholder = @UploadDialogResources.TypeInstructor })
            </div>
        </div>
        @Html.LabelFor(m => m.Description)
        @Html.TextAreaFor(m => m.Description, new { @class = "inputText commentTextarea academicDescription", id = "academicDescription" })

        <input type="submit" class="btn1 next"  value="@UploadDialogResources.Create"/>
        <button type="reset" class="btn2 cancel" id="cancel">@UploadDialogResources.Cancel</button>
    }
</div>

Zbang.Zbox.Mvc3WebRole/Views/Shared/Partials/_UploadCreateBox.cshtml
@using Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources
@model Zbang.Zbox.Mvc3WebRole.Models.CreateBox
<div id="createBoxDialog" title="Create new box" style="display: none;">
    @using (Html.BeginForm("Create", "Dashboard", FormMethod.Post, new { @class = "type personal ", id = "personal" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(false)

        @Html.LabelFor(m => m.BoxName, new { @class = "required" })
        @Html.TextBoxFor(m => m.BoxName, new { @class = "inputText boxName" })

        @Html.LabelFor(m => m.Description)
        @Html.TextAreaFor(m => m.Description, new { @class = "inputText commentTextarea" })
        <input type="submit" class="btn1 next"  value="@UploadDialogResources.Create"/>
        <button type="reset" class="btn2 cancel" id="cancel">@UploadDialogResources.Cancel</button>
    }
</div>


Zbang.Zbox.Mvc3WebRole/Views/Shared/Partials/_UploadDialog.cshtml
@using Zbang.Zbox.Mvc3WebRole.Views.Shared.Resources

@if (User.Identity.IsAuthenticated)
{
    <div class="popupWrppr" data-strap="uploadV2">
        <header class="popupHeader popupGradient">@UploadDialogResources.Upload</header>
        <div class="step2">
            <div class="newBoxForm">
                <span class="selectType">@UploadDialogResources.SelectType</span>
                <span class="toggleType">
                    <span class="selected">@UploadDialogResources.Academic</span>
                    <span>@UploadDialogResources.Personal</span>
                </span>
                <div class="sepV"></div>
                @{Html.RenderPartial("_UploadCreateAcademicBox", new Zbang.Zbox.Mvc3WebRole.Models.CreateAcademicBox());}
                @{Html.RenderPartial("_UploadCreateBox", new Zbang.Zbox.Mvc3WebRole.Models.CreateBox());}
                <div class="required label">@UploadDialogResources.RequiredField</div>
            </div>
        </div>
        <div class="step3">
            <div class="chooseTitle">
                @UploadDialogResources.ChooseFiles ‎“<span id="upldstep3BoxName" class="boxName"></span>”‎
            </div>
            <div class="dragDropBox" id="fileZone">
                <ul>
                </ul>
                <div class="dragDropTxtE" id="DragDropText">@UploadDialogResources.DragAndDrop</div>
                <button type="button" id="AddFiles" class="btn4">@UploadDialogResources.ChooseFile</button>
            </div>
            @{Html.RenderPartial("_UploadAddLink", new Zbang.Zbox.Mvc3WebRole.Models.AddLink());}
        </div>
        <button class="closeDialog shareSprite"></button>
        <input type="button" class="btn1 next" id="uploadNext" value="@UploadDialogResources.Next"/>
        <button class="btn2 cancel" id="cancel">@UploadDialogResources.Cancel</button>
    </div>
}